# Generated by Django 3.0.8 on 2020-08-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='company_hero_employees',
        ),
    ]
