# Generated by Django 3.0.8 on 2020-08-02 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_auto_20200802_1601'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='username',
            new_name='username_employee',
        ),
    ]
