# Generated by Django 3.0.8 on 2020-08-02 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0007_auto_20200802_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(blank=True, to='company.Company'),
        ),
    ]
