# Generated by Django 3.0.8 on 2020-08-03 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0008_auto_20200802_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ManyToManyField(to='company.Company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
