# Generated by Django 3.0.8 on 2020-08-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_auto_20200802_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='cpf',
            field=models.CharField(default='2020-04-12', max_length=11, unique=True, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='date_birth',
            field=models.DateField(default='2020-03-14', verbose_name='Data de Nascimento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nome completo'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='username',
            field=models.CharField(max_length=20, unique=True, verbose_name='Username'),
        ),
    ]
