from enum import Enum


class LogTypeSet(Enum):

    COMPANY_CREATE_PAYLOAD = 'COMPANY_CREATE_PAYLOAD'
    COMPANY_CREATE_RESPONSE = 'COMPANY_CREATE_RESPONSE'
    COMPANY_DELETE_PAYLOAD = 'COMPANY_DELETE_PAYLOAD'
    COMPANY_DELETE_RESPONSE = 'COMPANY_DELETE_RESPONSE'
    EMPLOYEE_CREATE_PAYLOAD = 'EMPLOYEE_CREATE_PAYLOAD'
    EMPLOYEE_CREATE_RESPONSE = 'EMPLOYEE_CREATE_RESPONSE'
    EMPLOYEE_DELETE_PAYLOAD = 'EMPLOYEE_DELETE_PAYLOAD'
    EMPLOYEE_DELETE_RESPONSE = 'EMPLOYEE_DELETE_RESPONSE'
