# Generated by Django 3.0.8 on 2020-07-31 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('fantasy_name', models.CharField(max_length=200)),
                ('cnpj', models.CharField(max_length=14)),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='common.Address')),
            ],
            options={
                'db_table': 'company_hero_company',
            },
        ),
    ]
